-- Sources du glossaire — SantéauMaroc
-- Généré le 2026-08-04 par scripts/export-glossary-sources-sql.ts
-- 79 termes sourcés sur 81 publiés.
--
-- Sûr et rejouable : n'écrase JAMAIS une source déjà présente en prod
-- (clause sources IS NULL OR '' OR '[]'), ne touche pas aux dates de relecture,
-- et n'insère aucune ligne. Un terme absent de la prod est simplement ignoré.

BEGIN;

-- État avant application (à comparer avec le compte final)
SELECT count(*) AS termes_sans_source_avant
  FROM glossary_terms
 WHERE status = 'PUBLISHED'
   AND (sources IS NULL OR sources = '' OR sources = '[]');

UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Maladies cardiovasculaires »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/cardiovascular-diseases-(cvds)","publisher":"OMS","year":"2025"}]' WHERE slug='avc' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Acné »","url":"https://www.ameli.fr/assure/sante/themes/acne","publisher":"ameli.fr"}]' WHERE slug='acne' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Anémie »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/anaemia","publisher":"OMS"},{"label":"Assurance Maladie — « Anémie par carence en fer »","url":"https://www.ameli.fr/assure/sante/themes/anemie-par-carence-en-fer","publisher":"ameli.fr"}]' WHERE slug='anemie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Bien utiliser les anti-inflammatoires non stéroïdiens »","url":"https://www.ameli.fr/assure/sante/medicaments/utiliser-recycler-medicaments/utiliser-anti-inflammatoires","publisher":"ameli.fr"}]' WHERE slug='anti-inflammatoire' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Résistance aux antimicrobiens »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/antimicrobial-resistance","publisher":"OMS"},{"label":"Assurance Maladie — « Bien utiliser les antibiotiques »","url":"https://www.ameli.fr/assure/sante/medicaments/utiliser-recycler-medicaments/bien-utiliser-les-antibiotiques/antibiotiques-et-antibioresistance","publisher":"ameli.fr"}]' WHERE slug='antibiotique' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Anticoagulants : importance du suivi »","url":"https://www.ameli.fr/assure/sante/medicaments/comprendre-les-differents-medicaments/anticoagulants","publisher":"ameli.fr"}]' WHERE slug='anticoagulant' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Médicaments pour le traitement de la dépression »","url":"https://www.msdmanuals.com/fr/accueil/troubles-mentaux/troubles-de-l-humeur/m%C3%A9dicaments-pour-le-traitement-de-la-d%C3%A9pression","publisher":"Manuel MSD"}]' WHERE slug='antidepresseur' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Allergies et antihistaminiques »","url":"https://www.ameli.fr/assure/sante/themes/allergie","publisher":"ameli.fr"}]' WHERE slug='antihistaminique' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Traitement de l''hypertension artérielle »","url":"https://www.ameli.fr/assure/sante/themes/hypertension-arterielle-hta","publisher":"ameli.fr"}]' WHERE slug='antihypertenseur' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Artériopathie oblitérante des membres inférieurs »","url":"https://www.ameli.fr/assure/sante/themes/arteriopathie-obliterante-arterite-des-membres-inferieurs","publisher":"ameli.fr"}]' WHERE slug='artere' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Arthrose »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/osteoarthritis","publisher":"OMS"},{"label":"Assurance Maladie — « Arthrose du genou »","url":"https://www.ameli.fr/assure/sante/themes/arthrose-genou","publisher":"ameli.fr"}]' WHERE slug='arthrose' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Caisse Nationale de Sécurité Sociale — « AMO, Assurance Maladie Obligatoire »","url":"https://www.cnss.ma/fr/assure/salarie/amo/informations-generale-amo","publisher":"CNSS Maroc"}]' WHERE slug='amo' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Asthme »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/asthma","publisher":"OMS","year":"2026"}]' WHERE slug='asthme' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Tests médicaux fréquents »","url":"https://www.msdmanuals.com/fr/accueil/ressources/tests-m%C3%A9dicaux-fr%C3%A9quents/tests-m%C3%A9dicaux-fr%C3%A9quents","publisher":"Manuel MSD"}]' WHERE slug='biopsie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Bronchite »","url":"https://www.ameli.fr/assure/sante/themes/bronchite","publisher":"ameli.fr"},{"label":"Assurance Maladie — « Bronchite aiguë »","url":"https://www.ameli.fr/assure/sante/themes/bronchite","publisher":"ameli.fr"}]' WHERE slug='bronchite' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Cancer du sein »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/breast-cancer","publisher":"OMS","year":"2026"}]' WHERE slug='cancer-du-sein' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Cécité et déficience visuelle »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/blindness-and-visual-impairment","publisher":"OMS"},{"label":"Assurance Maladie — « Cataracte »","url":"https://www.ameli.fr/assure/sante/themes/cataracte","publisher":"ameli.fr"}]' WHERE slug='cataracte' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Céphalées »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/headache-disorders","publisher":"OMS"},{"label":"Assurance Maladie — « Mal de tête »","url":"https://www.ameli.fr/assure/sante/themes/mal-tete","publisher":"ameli.fr"}]' WHERE slug='cephalee' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Chimiothérapie et autres traitements systémiques du cancer »","url":"https://www.msdmanuals.com/fr/accueil/cancer/pr%C3%A9vention-et-traitement-du-cancer/chimioth%C3%A9rapie-et-autres-traitements-syst%C3%A9miques-du-cancer","publisher":"Manuel MSD"}]' WHERE slug='chimiotherapie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Insuffisance cardiaque »","url":"https://www.ameli.fr/assure/sante/themes/insuffisance-cardiaque","publisher":"ameli.fr"}]' WHERE slug='coeur' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule une coloscopie ? »","url":"https://www.ameli.fr/assure/sante/examen/exploration/deroulement-coloscopie","publisher":"ameli.fr"}]' WHERE slug='coloscopie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Conjonctivite »","url":"https://www.ameli.fr/assure/sante/themes/conjonctivite","publisher":"ameli.fr"}]' WHERE slug='conjonctivite' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Cystite »","url":"https://www.ameli.fr/assure/sante/themes/cystite","publisher":"ameli.fr"}]' WHERE slug='cystite' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Prévention et dépistages »","url":"https://www.ameli.fr/assure/sante/assurance-maladie/prevention-depistages","publisher":"ameli.fr"}]' WHERE slug='depistage' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Trouble dépressif (dépression) »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/depression","publisher":"OMS","year":"2025"}]' WHERE slug='depression' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Diabète »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/diabetes","publisher":"OMS","year":"2024"}]' WHERE slug='diabete-type-2' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Dyspnée chronique ou essoufflement durable »","url":"https://www.ameli.fr/assure/sante/themes/dyspnee-chronique-ou-essoufflement-durable","publisher":"ameli.fr"}]' WHERE slug='dyspnee' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule une échographie ? »","url":"https://www.ameli.fr/assure/sante/examen/imagerie-medicale/deroulement-echographie-abdomino-pelvienne","publisher":"ameli.fr"}]' WHERE slug='echographie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Eczéma ou dermatite atopique »","url":"https://www.ameli.fr/assure/sante/themes/eczema-dermatite-atopique","publisher":"ameli.fr"},{"label":"Inserm — dossier « Dermatite atopique »","url":"https://www.inserm.fr/dossier/dermatite-atopique-eczema-atopique/","publisher":"Inserm"}]' WHERE slug='eczema' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Le médicament : ce qu''il faut savoir »","url":"https://www.ameli.fr/assure/sante/medicaments/comprendre-les-differents-medicaments/medicament","publisher":"ameli.fr"}]' WHERE slug='effet-secondaire' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Électrocardiogramme d''effort : déroulement »","url":"https://www.ameli.fr/assure/sante/examen/exploration/deroulement-electrocardiogramme-effort","publisher":"ameli.fr"}]' WHERE slug='electrocardiogramme' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule une endoscopie digestive haute ? »","url":"https://www.ameli.fr/assure/sante/examen/exploration/deroulement-endoscopie-digestive-haute","publisher":"ameli.fr"}]' WHERE slug='endoscopie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Épilepsie »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/epilepsy","publisher":"OMS"},{"label":"Inserm — dossier « Épilepsie »","url":"https://www.inserm.fr/dossier/epilepsie/","publisher":"Inserm"}]' WHERE slug='epilepsie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule un électrocardiogramme d''effort ? »","url":"https://www.ameli.fr/assure/sante/examen/exploration/deroulement-electrocardiogramme-effort","publisher":"ameli.fr"}]' WHERE slug='epreuve-d-effort' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Fièvre chez les adultes »","url":"https://www.msdmanuals.com/fr/accueil/infections/biologie-des-maladies-infectieuses/fi%C3%A8vre-chez-les-adultes","publisher":"Manuel MSD"}]' WHERE slug='fievre' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Stéatose hépatique »","url":"https://www.ameli.fr/assure/sante/themes/steatose-hepatique","publisher":"ameli.fr"}]' WHERE slug='foie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule un frottis du col utérin ? »","url":"https://www.ameli.fr/assure/sante/examen/gynecologie/deroulement-frottis-col-uterin","publisher":"ameli.fr"}]' WHERE slug='frottis' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Maladies diarrhéiques »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/diarrhoeal-disease","publisher":"OMS"},{"label":"Assurance Maladie — « Gastro-entérite de l''adulte »","url":"https://www.ameli.fr/assure/sante/themes/gastro-enterite-adulte","publisher":"ameli.fr"}]' WHERE slug='gastro-enterite' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Cécité et déficience visuelle »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/blindness-and-visual-impairment","publisher":"OMS"},{"label":"Assurance Maladie — « Glaucome »","url":"https://www.ameli.fr/assure/sante/themes/glaucome","publisher":"ameli.fr"}]' WHERE slug='glaucome' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Lire les résultats d''une prise de sang »","url":"https://www.ameli.fr/assure/sante/examen/analyse/lire-resultats-prise-sang","publisher":"ameli.fr"}]' WHERE slug='glycemie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Goutte »","url":"https://www.ameli.fr/assure/sante/themes/goutte","publisher":"ameli.fr"}]' WHERE slug='goutte' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Grippe saisonnière »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/influenza-(seasonal)","publisher":"OMS","year":"2025"}]' WHERE slug='grippe' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Hépatite B »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/hepatitis-b","publisher":"OMS","year":"2026"}]' WHERE slug='hepatite-b' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Lombalgie »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/low-back-pain","publisher":"OMS"},{"label":"Assurance Maladie — « Lombalgie aiguë »","url":"https://www.ameli.fr/assure/sante/themes/lombalgie-aigue","publisher":"ameli.fr"}]' WHERE slug='hernie-discale' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Hypertension artérielle »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/hypertension","publisher":"OMS","year":"2025"}]' WHERE slug='hypertension-arterielle' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Hypoglycémie »","url":"https://www.msdmanuals.com/fr/accueil/troubles-hormonaux-et-m%C3%A9taboliques/diab%C3%A8te-sucr%C3%A9-et-faible-taux-de-sucre-dans-le-sang-hypoglyc%C3%A9mie/hypoglyc%C3%A9mie","publisher":"Manuel MSD"}]' WHERE slug='hypoglycemie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Hypothyroïdie »","url":"https://www.ameli.fr/assure/sante/themes/hypothyroidie","publisher":"ameli.fr"}]' WHERE slug='hypothyroidie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Jaunisse chez l''adulte »","url":"https://www.msdmanuals.com/fr/accueil/troubles-du-foie-et-de-la-v%C3%A9sicule-biliaire/manifestations-cliniques-des-maladies-du-foie/jaunisse-chez-l-adulte","publisher":"Manuel MSD"}]' WHERE slug='ictere' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Obésité et surpoids »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/obesity-and-overweight","publisher":"OMS"}]' WHERE slug='imc' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Maladies cardiovasculaires »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/cardiovascular-diseases-(cvds)","publisher":"OMS"},{"label":"Assurance Maladie — « Infarctus du myocarde »","url":"https://www.ameli.fr/assure/sante/themes/infarctus-myocarde","publisher":"ameli.fr"}]' WHERE slug='infarctus-du-myocarde' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Maladies cardiovasculaires »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/cardiovascular-diseases-(cvds)","publisher":"OMS"},{"label":"Assurance Maladie — « Insuffisance cardiaque »","url":"https://www.ameli.fr/assure/sante/themes/insuffisance-cardiaque","publisher":"ameli.fr"}]' WHERE slug='insuffisance-cardiaque' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Traitement médicamenteux du diabète »","url":"https://www.msdmanuals.com/fr/accueil/troubles-hormonaux-et-m%C3%A9taboliques/diab%C3%A8te-sucr%C3%A9-et-faible-taux-de-sucre-dans-le-sang-hypoglyc%C3%A9mie/traitement-m%C3%A9dicamenteux-du-diab%C3%A8te","publisher":"Manuel MSD"}]' WHERE slug='insuline' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule une IRM ? »","url":"https://www.ameli.fr/assure/sante/examen/imagerie-medicale/deroulement-irm","publisher":"ameli.fr"}]' WHERE slug='irm' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Kinésithérapie du thorax »","url":"https://www.msdmanuals.com/fr/accueil/troubles-pulmonaires-et-des-voies-a%C3%A9riennes/r%C3%A9%C3%A9ducation-pour-les-troubles-des-poumons-et-des-voies-respiratoires/kin%C3%A9sith%C3%A9rapie-du-thorax","publisher":"Manuel MSD"}]' WHERE slug='kinesitherapie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule une mammographie ? »","url":"https://www.ameli.fr/assure/sante/examen/imagerie-medicale/deroulement-mammographie","publisher":"ameli.fr"}]' WHERE slug='mammographie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Céphalées »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/headache-disorders","publisher":"OMS"},{"label":"Assurance Maladie — « Migraine »","url":"https://www.ameli.fr/assure/sante/themes/migraine","publisher":"ameli.fr"}]' WHERE slug='migraine' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Obésité et surpoids »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/obesity-and-overweight","publisher":"OMS","year":"2025"}]' WHERE slug='obesite' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Jambes gonflées »","url":"https://www.ameli.fr/assure/sante/themes/jambes-lourdes","publisher":"ameli.fr"}]' WHERE slug='oedeme' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Lire une ordonnance de médicaments »","url":"https://www.ameli.fr/assure/sante/medicaments/utiliser-recycler-medicaments/lire-ordonnance-medicaments","publisher":"ameli.fr"}]' WHERE slug='ordonnance' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Ostéoporose »","url":"https://www.ameli.fr/assure/sante/themes/osteoporose","publisher":"ameli.fr"},{"label":"Inserm — dossier « Ostéoporose »","url":"https://www.inserm.fr/dossier/osteoporose/","publisher":"Inserm"}]' WHERE slug='osteoporose' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Palpitations cardiaques »","url":"https://www.ameli.fr/assure/sante/themes/palpitations-cardiaques","publisher":"ameli.fr"}]' WHERE slug='palpitations' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Pneumonie »","url":"https://www.ameli.fr/assure/sante/themes/pneumonie","publisher":"ameli.fr"}]' WHERE slug='pneumonie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Présentation du système respiratoire »","url":"https://www.msdmanuals.com/fr/accueil/troubles-pulmonaires-et-des-voies-a%C3%A9riennes/biologie-des-poumons-et-des-voies-respiratoires/pr%C3%A9sentation-du-syst%C3%A8me-respiratoire","publisher":"Manuel MSD"}]' WHERE slug='poumons' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Lire les résultats d''une prise de sang »","url":"https://www.ameli.fr/assure/sante/examen/analyse/lire-resultats-prise-sang","publisher":"ameli.fr"}]' WHERE slug='prise-de-sang' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Adénome de la prostate »","url":"https://www.ameli.fr/assure/sante/themes/adenome-prostate","publisher":"ameli.fr"}]' WHERE slug='prostate' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Psoriasis »","url":"https://www.ameli.fr/assure/sante/themes/psoriasis","publisher":"ameli.fr"},{"label":"Inserm — dossier « Psoriasis »","url":"https://www.inserm.fr/dossier/psoriasis/","publisher":"Inserm"}]' WHERE slug='psoriasis' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Radiographies »","url":"https://www.msdmanuals.com/fr/accueil/sujets-particuliers/examens-d-imagerie-courants/radiographies","publisher":"Manuel MSD"}]' WHERE slug='radiographie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Radiothérapie pour le cancer »","url":"https://www.msdmanuals.com/fr/accueil/cancer/pr%C3%A9vention-et-traitement-du-cancer/radioth%C3%A9rapie-pour-le-cancer","publisher":"Manuel MSD"}]' WHERE slug='radiotherapie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Manuel MSD, version grand public — « Reflux gastro-œsophagien (RGO) »","url":"https://www.msdmanuals.com/fr/accueil/troubles-digestifs/maladies-de-l-%C5%93sophage-et-de-la-d%C3%A9glutition/reflux-gastro-%C5%93sophagien-rgo","publisher":"Manuel MSD"}]' WHERE slug='reflux-gastro-oesophagien' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Maladie rénale chronique »","url":"https://www.ameli.fr/assure/sante/themes/maladie-renale-chronique","publisher":"ameli.fr"}]' WHERE slug='rein' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Comment se déroule un scanner ? »","url":"https://www.ameli.fr/assure/sante/examen/imagerie-medicale/deroulement-scanner","publisher":"ameli.fr"}]' WHERE slug='scanner' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Sciatique »","url":"https://www.ameli.fr/assure/sante/themes/sciatique","publisher":"ameli.fr"}]' WHERE slug='sciatique' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Trouble du rythme cardiaque »","url":"https://www.ameli.fr/assure/sante/themes/trouble-rythme-cardiaque","publisher":"ameli.fr"}]' WHERE slug='tachycardie' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « La télémédecine »","url":"https://www.ameli.fr/assure/remboursements/rembourse/consultations-telemedecine/telemedecine","publisher":"ameli.fr"}]' WHERE slug='teleconsultation' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Troubles de la thyroïde »","url":"https://www.ameli.fr/assure/sante/themes/hypothyroidie","publisher":"ameli.fr"}]' WHERE slug='thyroide' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Organisation mondiale de la Santé — « Tuberculose »","url":"https://www.who.int/fr/news-room/fact-sheets/detail/tuberculosis","publisher":"OMS","year":"2026"}]' WHERE slug='tuberculose' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Vaccination »","url":"https://www.ameli.fr/assure/sante/themes/vaccination","publisher":"ameli.fr"}]' WHERE slug='vaccin' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Varices des jambes »","url":"https://www.ameli.fr/assure/sante/themes/varices-jambes","publisher":"ameli.fr"}]' WHERE slug='varices' AND (sources IS NULL OR sources = '' OR sources = '[]');
UPDATE glossary_terms SET sources='[{"label":"Assurance Maladie — « Vertiges »","url":"https://www.ameli.fr/assure/sante/themes/vertiges","publisher":"ameli.fr"}]' WHERE slug='vertige' AND (sources IS NULL OR sources = '' OR sources = '[]');

-- Contrôle : ce compte doit avoir chuté d'autant de lignes que d'UPDATE appliqués
SELECT count(*) AS termes_sans_source_apres
  FROM glossary_terms
 WHERE status = 'PUBLISHED'
   AND (sources IS NULL OR sources = '' OR sources = '[]');

COMMIT;
